In [3]:
import pods
import zipfile
import sys
import pandas as pd
import numpy as np

pods.util.download_url("http://files.grouplens.org/datasets/movielens/ml-latest-small.zip")
zip_console = zipfile.ZipFile('ml-latest-small.zip', 'r')
for name in zip_console.namelist():
           zip_console.extract(name, './')

[==============================]   0.933/0.933MB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

# how many user?
# cvs contain:
# userId, movieId, rating and tags

In [21]:
YourStudentID = 20  # Include here the last three digits of your UCard number
nUsersInExample = 10 # The maximum number of Users we're going to analyse at one time

ratings = pd.read_csv("./ml-latest-small/ratings.csv") 
# ratings.columns

# every time run the code it generate the same random number

In [22]:
# ratings is a DataFrame with four columns: userId, movieId, rating and tags. 

# We first want to identify how many unique users there are. 

# We can use the unique method in pandas

indexes_unique_users = ratings['userId'].unique()
n_users = indexes_unique_users.shape[0] # 610

## mix the random number
## take the first num of nUsersInExample elements

In [42]:
# We randomly select 'nUsers' users with their ratings. We first fix the seed
# of the random generator to make sure that we always get the same 'nUsers'

np.random.seed(YourStudentID)
indexes_users = np.random.permutation(n_users)
my_batch_users = indexes_users[0:nUsersInExample]
# print(indexes_users)
# print("-------------------------")
print(my_batch_users)

[119 584 416 304 397  14  94 529 543  13]


## _ is a variable generate the empty list for films & ratings of each user

In [24]:
# We will use now the list of 'my_batch_users' to create a matrix Y. 

# We need to make a list of the movies that these users have watched
list_movies_each_user = [[] for _ in range(nUsersInExample)]
list_ratings_each_user = [[] for _ in range(nUsersInExample)]

## Movies
    list_movies:
        find the movieID from the userID that we selected
        Then give it to "list_movies_each_user[0]"


In [ ]:
# Movies
list_movies = ratings['movieId'][ratings['userId'] == my_batch_users[0]].values
list_movies_each_user[0] = list_movies    

## Ratings
    list_ratings:
        find the movieID from the userID that we selected
        Then give it to "list_ratings_each_user[0]"

In [43]:
# Ratings                      
list_ratings = ratings['rating'][ratings['userId'] == my_batch_users[0]].values
list_ratings_each_user[0] = list_ratings

array([119, 584, 416, 304, 397,  14,  94, 529, 543,  13])

## User
    shape[0] is the total num of row
    shape[1] is the total num of column
    
    my_batch_users 10 people we selected
    
    list_users:
        n_each_user * the elements of first 10
    np.ones((1, n_each_user)) generate the 1D and total num of n_each_user of array

In [45]:
# Users
n_each_user = list_movies.shape[0]
list_users = my_batch_users[0]*np.ones((1, n_each_user))
print(list_users)

[[119. 119. 119. ... 119. 119. 119.]]


    for loop to fill in the remaining 1-9 into
        list_movies
        list_ratings
        list_users

In [36]:
for i in range(1, nUsersInExample):
    # Movies
    local_list_per_user_movies = ratings['movieId'][ratings['userId'] == my_batch_users[i]].values
    list_movies_each_user[i] = local_list_per_user_movies
    list_movies = np.append(list_movies,local_list_per_user_movies)
    # Ratings                                 
    local_list_per_user_ratings = ratings['rating'][ratings['userId'] == my_batch_users[i]].values
    list_ratings_each_user[i] = local_list_per_user_ratings
    list_ratings = np.append(list_ratings, local_list_per_user_ratings)  
    # Users                                   
    n_each_user = local_list_per_user_movies.shape[0]                                                                               
    local_rep_user =  my_batch_users[i]*np.ones((1, n_each_user))
    print(local_rep_user)
    list_users = np.append(list_users, local_rep_user)

[[584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584.
  584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584.
  584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584.
  584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584.
  584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584.
  584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584. 584.]]
[[416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416.
  416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416.
  416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416. 416.
  416. 416. 416. 416. 416. 416. 416. 416. 416.]]
[[304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304.
  304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304.
  304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304.
  304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304. 304.
  304. 304. 304. 3

    pd.DataFrame：
        generate a D array

    Y_with_NaNs
        row num of unique movies (600)
        column num of users (10)
    np.in1d(indexes_unique_movies, local_movies)
    match the value in indexes_unique_movies from the value in local_movies

In [27]:
# Let us first see how many unique movies have been rated
indexes_unique_movies = np.unique(list_movies)
n_movies = indexes_unique_movies.shape[0]
# As it is expected no all users have rated all movies. We will build a matrix Y 
# with NaN inputs and fill according to the data for each user 
temp = np.empty((n_movies,nUsersInExample,))
temp[:] = np.nan
Y_with_NaNs = pd.DataFrame(temp)
for i in range(nUsersInExample):
    local_movies = list_movies_each_user[i]
    ixs = np.in1d(indexes_unique_movies, local_movies)
    Y_with_NaNs.loc[ixs, i] = list_ratings_each_user[i]

Y_with_NaNs.index = indexes_unique_movies.tolist()
Y_with_NaNs.columns = my_batch_users.tolist()

    from multi D to 1D
        ravel()：如果没有必要，不会产生源数据的副本
        flatten()：返回源数据的副本
        squeeze()：只能对维数为1的维度降维


    线性回归的最佳方式是将数据拆分成很多小批次。每个批次都大概具有相同数量的数据点。然后使用每个批次更新权重。这种方法叫做小批次梯度下降法。

In [28]:
p_list_ratings = np.concatenate(list_ratings_each_user).ravel()
p_list_ratings_original = p_list_ratings.tolist()
mean_ratings_train = np.mean(p_list_ratings)
p_list_ratings =  p_list_ratings - mean_ratings_train # remove the mean
p_list_movies = np.concatenate(list_movies_each_user).ravel().tolist()
p_list_users = list_users.tolist()
Y = pd.DataFrame({'users': p_list_users, 'movies': p_list_movies, 'ratingsorig': p_list_ratings_original,'ratings':p_list_ratings.tolist()})

In [29]:
Y

users  movies  ratingsorig   ratings
0    119.0       1          3.5 -0.367718
1    119.0      10          4.0  0.132282
2    119.0      44          3.0 -0.867718
3    119.0     170          5.0  1.132282
4    119.0     173          3.0 -0.867718
..     ...     ...          ...       ...
819   13.0    3952          3.0 -0.867718
820   13.0    3977          3.0 -0.867718
821   13.0    3996          5.0  1.132282
822   13.0    4011          5.0  1.132282
823   13.0    4148          4.0  0.132282

[824 rows x 4 columns]

In [ ]:
q = 2 # the dimension of our map of the 'library'
learn_rate = 0.01
U = pd.DataFrame(np.random.normal(size=(nUsersInExample, q))*0.001, index=my_batch_users)
V = pd.DataFrame(np.random.normal(size=(n_movies, q))*0.001, index=indexes_unique_movies)

In [ ]:
def objective_gradient(Y, U, V):
    gU = pd.DataFrame(np.zeros((U.shape)), index=U.index)
    gV = pd.DataFrame(np.zeros((V.shape)), index=V.index)
    obj = 0.
    nrows = Y.shape[0]
    for i in range(nrows):
        row = Y.iloc[i]
        user = row['users']
        film = row['movies']
        rating = row['ratings']
        prediction = np.dot(U.loc[user], V.loc[film]) # vTu
        diff = prediction - rating # vTu - y
        obj += diff*diff
        gU.loc[user] += 2*diff*V.loc[film]
        gV.loc[film] += 2*diff*U.loc[user]
    return obj, gU, gV

In [ ]:
iterations = 50
for i in range(iterations):
    obj, gU, gV = objective_gradient(Y, U, V)
    print("Iteration", i, "Objective function: ", obj)
    U -= learn_rate*gU
    V -= learn_rate*gV   

In [ ]:
# Question 6 Code Answer

def prediction(Y,U,V):
    pred_df = pd.DataFrame(index = Y.index, columns = ['prediction'])
    abs_error_df = pd.DataFrame(index = Y.index, columns = ['absolute error'])
    for i in Y.index:
        row = Y.iloc[i]
        user = row['users']
        film = row['movies']
        rating = row['ratings']
        pred_df.loc[i] = np.dot(U.loc[user], V.loc[film]) # vTu
        abs_error_df.loc[i] = abs(pred_df.iloc[i, 0]-rating)
        
    return pred_df, abs_error_df

pred_df, abs_error_df = prediction(Y, U, V)
Y['prediction'] = pred_df
Y['absolute error'] = abs_error_df

In [ ]:
Y

In [ ]:
# Question 7 Code Answer
import matplotlib.pylab as plt
%matplotlib inline

def compute_obj(Y, U, V):
    obj = 0
    for i in Y.index:
        row = Y.iloc[i]
        user = row['users']
        film = row['movies']
        rating = row['ratings']
        prediction = np.dot(U.loc[user], V.loc[film]) # vTu
        diff = prediction - rating # vTu - y
        obj += diff*diff
    return obj

def obj_gradient(rating, u, v):
    prediction = np.dot(u, v)
    diff = prediction - rating
    gU = 2* diff * v
    gV = 2* diff * u

    return gU, gV


def SGD(Y, U, V, learn_rate = 0.01, max_iter = 100, check_obj = 1000):
    update_counter = 0
    obj_prev = None
    converge = False
    
    num_updates = []
    objectives = []
    idx_list = Y.index.values
    for iteration in range(max_iter):
        if converge:
            break
        np.random.shuffle(idx_list)
        for i in idx_list:
            if converge:
                break
            row = Y.iloc[i]
            user = row['users']
            film = row['movies']
            rating = row['ratings']            
            gU, gV = obj_gradient(rating, U.loc[user], V.loc[film])
            U.loc[user] -= learn_rate * gU
            V.loc[film] -= learn_rate * gV 
            update_counter += 1
            if update_counter %check_obj == 0:
                obj = compute_obj(Y, U, V)
                num_updates.append(update_counter)
                objectives.append(obj)
                print('Update %s times, objective %s'%(update_counter, obj))
                if obj_prev == None or obj_prev > obj:
                    obj_prev = obj
                else:
                    converge = True
                    
    plt.plot(num_updates, objectives, 'rx-')
    plt.title('Objectives over updates')
    plt.show()
                    
    return U, V                
            
    
q = 2
U = pd.DataFrame(np.random.normal(size=(nUsersInExample, q))*0.001, index=my_batch_users)
V = pd.DataFrame(np.random.normal(size=(n_movies, q))*0.001, index=indexes_unique_movies)

U, V = SGD(Y, U, V)

In [ ]:
plt.plot(V[0],V[1],'rx')
plt.title('Movie map')
plt.show()

plt.plot(U[0],U[1],'bx')
plt.title('User map')
plt.show()

In [ ]:
# Code for question 8 here.
ratings = pd.read_csv("./ml-latest-small/ratings.csv") 
Y_full = pd.DataFrame({'users': ratings['userId'], 'movies': ratings['movieId'], 'ratingsorig': ratings['rating']})
Y_full['ratings'] = Y_full['ratingsorig'] - np.mean(Y_full['ratingsorig'])
indexes_unique_users = ratings['userId'].unique()
n_users = indexes_unique_users.shape[0]
indexes_unique_movies = ratings['movieId'].unique()
n_movies = indexes_unique_movies.shape[0]
q = 2
U = pd.DataFrame(np.random.normal(size=(n_users, q))*0.001, index=indexes_unique_users)
V = pd.DataFrame(np.random.normal(size=(n_movies, q))*0.001, index=indexes_unique_movies)

# max_iter should be larger, we just put 10 here for making it faster.
U, V = SGD(Y_full, U, V, max_iter = 10, check_obj = Y_full.shape[0]) # more iterations are needed for optimization

In [ ]:
plt.plot(V[0],V[1],'rx')
plt.title('Movie map')
plt.show()